# Generated by Django 4.0.3 on 2023-05-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.CharField(choices=[('librarian', 'librarian'), ('member', 'member')], default='member', max_length=10),
        ),
    ]
